### ISSUE TITLE
not opening

### ISSUE THREAD

**Issue by mfrw-mf** [start-5/TiTS.JS-Save-Editor#85] opened 2023-06-08 20:07 UTC
it give me this (
Message: $ is not defined
Stacktrace: ReferenceError: $ is not defined
at https://start-5.github.io/TiTS.JS-Save-Editor/:150:9)

**Comment by mfrw-mf** [comment] 2023-06-16 11:56
Message: $ is not defined
Stacktrace: ReferenceError: $ is not defined
    at https://start-5.github.io/TiTS.JS-Save-Editor/:150:9

**Comment by start-5** [comment] 2023-06-16 12:28
Duplicate of #84

**Closed by start-5** 2023-06-16 12:28 UTC

**Comment by mfrw-mf** [comment] 2023-06-20 04:51
so how do i fix it

**Comment by mfrw-mf** [comment] 2023-06-20 04:51
it is still not working
